### ISSUE TITLE
fail to load sbt project

### ISSUE THREAD

**Issue by intracer** [scalafx/ProScalaFX#10]
$ sbt compile
[info] Loading global plugins from /home/ilya/.sbt/0.13/plugins
[info] Updating {file:/home/ilya/.sbt/0.13/plugins/}global-plugins...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Loading project definition from /home/ilya/wm/fx/ProScalaFX/project
[info] Updating {file:/home/ilya/wm/fx/ProScalaFX/project/}proscalafx-build...
[info] Resolving org.scala-lang#scalap;2.10.5 ...
[info] Done updating.
[info] Set current project to ProScalaFX (in build file:/home/ilya/wm/fx/ProScalaFX/)
[info] Updating {file:/home/ilya/wm/fx/ProScalaFX/}proscalafx...
[info] Resolving org.scalafx#scalafx_2.11;8.0.60-R9-SNAPSHOT ...
[warn]  module not found: org.scalafx#scalafx_2.11;8.0.60-R9-SNAPSHOT
[warn] ==== local: tried
[warn]   /home/ilya/.ivy2/local/org.scalafx/scalafx_2.11/8.0.60-R9-SNAPSHOT/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/scalafx/scalafx_2.11/8.0.60-R9-SNAPSHOT/scalafx_2.11-8.0.60-R9-SNAPSHOT.pom
[warn] ==== sonatype-snapshots: tried
[warn]   https://oss.sonatype.org/content/repositories/snapshots/org/scalafx/scalafx_2.11/8.0.60-R9-SNAPSHOT/scalafx_2.11-8.0.60-R9-SNAPSHOT.pom
[info] Resolving org.scala-lang#scalap;2.11.7 ...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.scalafx#scalafx_2.11;8.0.60-R9-SNAPSHOT: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn]  Note: Unresolved dependencies path:
[warn]      org.scalafx:scalafx_2.11:8.0.60-R9-SNAPSHOT (/home/ilya/wm/fx/ProScalaFX/build.sbt#L24-25)
[warn]        +- default:proscalafx_2.11:8.0.60-R9-SNAPSHOT
sbt.ResolveException: unresolved dependency: org.scalafx#scalafx_2.11;8.0.60-R9-SNAPSHOT: not found
    at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:294)
    at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:191)
    at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:168)
    at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
    at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
    at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:132)
    at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
    at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
    at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
    at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
    at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
    at xsbt.boot.Using$.withResource(Using.scala:10)
    at xsbt.boot.Using$.apply(Using.scala:9)
    at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
    at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
    at xsbt.boot.Locks$.apply0(Locks.scala:31)
    at xsbt.boot.Locks$.apply(Locks.scala:28)
    at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
    at sbt.IvySbt.withIvy(Ivy.scala:127)
    at sbt.IvySbt.withIvy(Ivy.scala:124)
    at sbt.IvySbt$Module.withModule(Ivy.scala:155)
    at sbt.IvyActions$.updateEither(IvyActions.scala:168)
    at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1392)
    at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1388)
    at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$90.apply(Defaults.scala:1422)
    at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$90.apply(Defaults.scala:1420)
    at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
    at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1425)
    at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1419)
    at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
    at sbt.Classpaths$.cachedUpdate(Defaults.scala:1442)
    at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1371)
    at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1325)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:235)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
[error](*:update) sbt.ResolveException: unresolved dependency: org.scalafx#scalafx_2.11;8.0.60-R9-SNAPSHOT: not found
[error] Total time: 2 s, completed Mar 22, 2016 6:55:12 PM

**Comment by robert-blankenship** [comment]
Same error here

**Comment by robert-blankenship** [comment]
PR is up https://github.com/scalafx/ProScalaFX/pull/12

@intracer as a workaround, modify the build.sbt to use the following:

`libraryDependencies += "org.scalafx" %% "scalafx" % "8.0.60-R9"`

rather than

`libraryDependencies += "org.scalafx" %% "scalafx" % "8.0.60-R9-SNAPSHOT"`
